#!/usr/bin/with-contenv bashio
# ==============================================================================
# German TV Panel – Add-on startup script
# Liest /data/options.json direkt via Python und schreibt channels.js
# ==============================================================================

bashio::log.info "Starting German TV Panel..."

# ── Generate channels.js from /data/options.json via Python ──────────────────
python3 - << 'PYEOF'
import json, sys, os

OPTIONS_FILE = "/data/options.json"
OUTPUT_FILE  = "/usr/share/nginx/html/channels.js"

try:
    with open(OPTIONS_FILE, "r", encoding="utf-8") as f:
        options = json.load(f)
except Exception as e:
    print(f"[german_tv] ERROR reading {OPTIONS_FILE}: {e}", file=sys.stderr)
    options = {}

channels = options.get("channels", [])

if not channels:
    print("[german_tv] WARNING: No channels found in options.json!", file=sys.stderr)
else:
    print(f"[german_tv] Loaded {len(channels)} channel(s).")

# Sicher als JS-Datei schreiben (ensure_ascii=False für Umlaute)
js_content = (
    "// Auto-generated by run.sh – do not edit manually.\n"
    "// Edit channels in the Add-on configuration in Home Assistant.\n"
    f"window.TV_CHANNELS = {json.dumps(channels, ensure_ascii=False, indent=2)};\n"
)

os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"[german_tv] channels.js written to {OUTPUT_FILE}")
PYEOF

# ── Start nginx ───────────────────────────────────────────────────────────────
bashio::log.info "Starting nginx..."
exec nginx -g "daemon off;"
