#!/usr/bin/with-contenv bashio
# ==============================================================================
# German TV Panel – Add-on startup script
# Reads the channel configuration from /data/options.json and generates
# the channels.js file used by the frontend, then starts nginx.
# ==============================================================================

bashio::log.info "Starting German TV Panel..."

# ── Read options and generate channels.js ─────────────────────────────────────
CHANNELS_JSON=$(bashio::config 'channels')
INGRESS_ENTRY=$(bashio::addon.ingress_entry)

bashio::log.info "Ingress entry: ${INGRESS_ENTRY}"
bashio::log.info "Loaded $(echo "${CHANNELS_JSON}" | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))') channel(s)."

# Write channels as a JS file so the frontend can import it without a build step
cat > /usr/share/nginx/html/channels.js << EOF
// Auto-generated by run.sh – do not edit manually.
// Edit channels in the Add-on configuration UI or in your options.json.
window.TV_CHANNELS = ${CHANNELS_JSON};
window.INGRESS_ENTRY = "${INGRESS_ENTRY}";
EOF

# ── Patch nginx ingress path ──────────────────────────────────────────────────
# HA ingress proxies the add-on under a dynamic path like /api/hassio_ingress/<token>/
# nginx needs to know this base path for correct asset resolution.
sed -i "s|__INGRESS_ENTRY__|${INGRESS_ENTRY}|g" /etc/nginx/nginx.conf

# ── Start nginx ───────────────────────────────────────────────────────────────
bashio::log.info "Starting nginx..."
exec nginx -g "daemon off;"
